Joined processes
caravelahc/paratex pull request #19
Opened 2019-10-31 23:06 UTC by GabrielSimonetto

Added:

join_parts.py --> when you want to join csvs that are already separated by session
joined_process on __main__.py --> if you wanna save it all together when scrapping the data

2019-11-04 18:46 UTC, JPTIZ requested changes
Esse vou deixar você resolver :)

2019-11-04 18:46 UTC, JPTIZ commented on paratex/__main__.py
> +PARTITIONED_PATH.mkdir(parents=True, exist_ok=True)
Não rode comandos no meio do arquivo, pelo amorzinho de Desu >:(

2019-11-04 18:46 UTC, JPTIZ commented on paratex/__main__.py
> +JOINED_PATH.mkdir(parents=True, exist_ok=True)
O mesmo aqui >:( Scripts são pra fornecer coisas, execuções são só no `if __name__ == '__main__':`. Eu não quero ter pastas criadas por dar `import *something*`.

2019-11-04 18:46 UTC, JPTIZ commented on paratex/__main__.py
> +def partitioned_process(sessions):
Se for o caso de criar a pasta, faça aqui:

```suggestion
def partitioned_process(sessions):
    PARTITIONED_PATH.mkdir(parents=True, exist_ok=True)
```

2019-11-04 18:46 UTC, JPTIZ commented on paratex/__main__.py
> +def joined_process(sessions, interval_begin, interval_end):
O mesmo aqui:

```suggestion
def joined_process(sessions, interval_begin, interval_end):
    JOINED_PATH.mkdir(parents=True, exist_ok=True)    
```

2019-11-04 18:46 UTC, JPTIZ commented on paratex/__main__.py
> +            print('Building', f"{dataframe.iloc[1, 3]}.csv", end='\r')
```suggestion
            print(f'Building {dataframe.iloc[1, 3]}.csv}', end='\r')
```

2019-11-04 18:46 UTC, JPTIZ commented on paratex/__main__.py
> +    """partitioned_mode: If output should segment csvs for each session"""
```suggestion
    '''partitioned_mode: True makes output splitted into a CSV file for each session, False joins sessions into a single CSV.'''
```

2019-11-04 19:36 UTC, GabrielSimonetto commented
Percebi que a gente tava se repetindo com as constantes... resolvi assim, vc acha que tudo bem?

em `__main__.py`
```
from join_parts import PARTITIONED_PATH, JOINED_PATH
```

em `join_parts.py`
```
PARTITIONED_PATH = Path(__file__).parent / 'partitioned_csvs'
JOINED_PATH = Path(__file__).resolve().parent.joinpath('joined_csvs')
```

Se um dia o main e o join_parts ficarem em pastas separadas, o `__file__` escolhido é o do join_parts né?

Tu faria assim tambem? Ou prefere inverter os 2?

2019-11-05 17:53 UTC, JPTIZ commented
> Percebi que a gente tava se repetindo com as constantes... resolvi assim, vc acha que tudo bem?
> 
> em `__main__.py`
> 
> ```
> from join_parts import PARTITIONED_PATH, JOINED_PATH
> ```
> 
> em `join_parts.py`
> 
> ```
> PARTITIONED_PATH = Path(__file__).parent / 'partitioned_csvs'
> JOINED_PATH = Path(__file__).resolve().parent.joinpath('joined_csvs')
> ```

Não chega a ser necessário ter um arquivo `join_paths.py`, mas seria interessante algum `export.py` (ou `report.py`) feito para a parte de exportar dados.

> Se um dia o main e o join_parts ficarem em pastas separadas, o `__file__` escolhido é o do join_parts né?

Aliás, será que não seria melhor aproveitar o `cwd` em vez das pastas do pacote?

> Tu faria assim tambem? Ou prefere inverter os 2?

Eu faria as funções receberem um `path: Path` por parâmetro, e aí só setar `PARTITIONED_PATH` e `JOINED_PATH` como defaults.


---

Por sinal, não entendi por que cê comentou o `if __name__ == '__main__': main()` do `__main__.py`. Você pode ter esse `if` em mais de um arquivo do mesmo projeto sem problemas.

2019-11-05 19:10 UTC, GabrielSimonetto commented
> Não chega a ser necessário ter um arquivo join_paths.py, mas seria interessante algum export.py (ou report.py) feito para a parte de exportar dados.

Mas o join_paths já existe, é o arquivo que concatena os csvs se eles ja foram criados separadamente

> Aliás, será que não seria melhor aproveitar o cwd em vez das pastas do pacote?

Cwd no lugar de file daí? Mas não fica um problema similar depois disso?

2020-02-05 02:41 UTC, JPTIZ approved these changes

2020-02-05 02:45 UTC, JPTIZ commented
Okay, mudei algumas coisinhas menores (tinha uma documentação em pt-br no meio do código em inglês, e volta e meia se usava aspas duplas em vez de simples - ao contrário do resto inteiro do projeto).

A partir daqui a gente abre issues pras coisas que discutimos na thread, formalizamos uma APIzinha bacana e enquanto isso partimos pra um Flask.

2020-02-05 02:45 UTC, merged