Some random code corrections
caravelahc/paratex pull request #22
Opened 2020-10-28 00:50 UTC by patrickelectric

2020-10-28 00:51 UTC, patrickelectric commented
@GabrielSimonetto @JPTIZ random code corrections, I was unable to run it without these changes

2020-11-08 20:20 UTC, GabrielSimonetto approved these changes
LGTM!

2020-11-08 20:21 UTC, JPTIZ approved these changes

2020-11-08 20:22 UTC, JPTIZ requested changes
Needs rebase.

2021-01-27 00:19 UTC, merged