cleanup
caravelahc/paratex pull request #24
Opened 2021-01-27 01:18 UTC by JPTIZ

- Remove unused code
- Slightly enhance and fix a few documentations

2021-01-29 16:17 UTC, GabrielSimonetto requested changes
Just some typos and stuff

2021-01-29 16:17 UTC, GabrielSimonetto commented on paratex/extractor.py
> +    columns.
```suggestion
    Accesses a session's attendance page URL and returns the attendance table
    columns.
```

2021-01-29 16:17 UTC, GabrielSimonetto commented on paratex/extractor.py
> +            "http://transparencia.alesc.sc.gov.br/" "presenca_plenaria_detalhes.php"
```suggestion
            "http://transparencia.alesc.sc.gov.br/presenca_plenaria_detalhes.php"
```

This max line size on black sounds a bit big no? I preferred the 2 line break here

2021-02-02 16:36 UTC, JPTIZ commented
These issues should be fixed now.

2021-02-06 17:47 UTC, GabrielSimonetto approved these changes
Nice!

2021-02-06 18:00 UTC, merged