Fix tests and fetch sessions from interval from same month
caravelahc/paratex pull request #29
Opened 2021-10-02 21:29 UTC by gabrieltron

2021-10-09 03:51 UTC, JPTIZ approved these changes
Way better than the previous solution. Very nice :)

2021-10-09 21:56 UTC, GabrielSimonetto requested changes
Amei os testes :pineapple:

2021-10-09 21:56 UTC, GabrielSimonetto commented on paratex/date_utils.py
> +    """
Eu gostaria que essa docstring dissesse se os limites sao exclusivos ou inclusivos

2021-10-09 21:56 UTC, GabrielSimonetto commented on paratex/extractor.py
> +        sessions += fetch_session(url)
Essa operação nao é idêntica ao append :D

O main nessa versão do código quebra, pois o retorno dessa função deixa de ser uma `Lista de Lista de Tuplas` para somente uma `Lista de Tuplas`

(o que me faz pensar inclusive que o tipo de retorno ali em cima ta errado, fucking hell...)

```
In [3]: fetch_session_result = [(1,1), (2,2)]                                         

In [4]: before = list()                                                               

In [5]: before.append(fetch_session_result)                                           

In [6]: before                                                                        
Out[6]: [[(1, 1), (2, 2)]]

In [7]: after = list()                                                                

In [8]: after += fetch_session_result                                                 

In [9]: after                                                                         
Out[9]: [(1, 1), (2, 2)]
```

O que me deixa triste pq teus testes estao lindos e nao tinha um teste cuidando dessa função pra ti, tu dá uma olhada nesse rolê?

2021-10-09 22:43 UTC, gabrieltron commented on paratex/extractor.py
> +        sessions += fetch_session(url)
Então, sim, não é. Mas o que eu pensei foi, faz sentido esse método retornar uma lista de listas? Pensando em como esse método vai ser chamado, as sessões estarem dentro de uma lista de listas faz com que a função que chame tenha que fazer algo tipo `sessions = fetch_sessions_from_interval(interval)[0]` pra de fato ter a lista de sessões. Aí justamente porque não existiam testes, pensei que esse comportamento de append não era intencional, e que o comportamento do `+=` seria mais adequado.

O que achas? Se for realmente interessante que o método retorne uma lista de listas posso mudar tho

2021-10-09 23:57 UTC, GabrielSimonetto commented on paratex/extractor.py
> +        sessions += fetch_session(url)
Realmente, tem duas funções que usam esse treco na main: `joined_process` e `partitioned_process` (also pq diabo isso ta na main), e nenhuma das duas ta usando a distinção hierarquica, ambos só querem chegar no dado

```
    for month in sessions:
        for session in month:
            session_id = session[0]
            // ... and month is never used anymore            
```

Entao eu nao tenho nem ideia de porque costumava ter 2 niveis hierarquicos e imagino que é completamente ok flattenar esse treco, inclusive acho que pra consertar é só questão de remover o for do mes hehehe

2021-10-13 23:15 UTC, JPTIZ commented on paratex/extractor.py
> +        sessions += fetch_session(url)
Concordo em manter unidimensional. Inclusive, bom perceber que antes a anotação de tipos estava incorreta (talvez a gente devesse ter rodado `mypy` mais vezes :^) ora ora).

O fato de ter 2 níveis antes era ou pra separar por mês (meio nada a ver) ou por uso incorreto de `append` onde deveria ser `extend`.

2021-10-13 23:17 UTC, JPTIZ commented on paratex/date_utils.py
> +    """
```suggestion
    """Get the months from a start date to a end date.

    Returns:
        Iterator over tuples containing the month and its year, respectively
    """
```

Isso já deixaria claro que é inclusivo :)

2022-01-07 19:11 UTC, merged

2022-01-07 19:11 UTC, JPTIZ commented
:tada: Happy new year :)